# Define the main LaTeX file name (without extension)
TEX_FILE = main

# Define the output PDF file name
PDF_FILE = $(TEX_FILE).pdf

# Define the LaTeX compiler to use
LATEX_COMPILER = pdflatex

# List common auxiliary files generated by LaTeX that should be cleaned
AUX_FILES = \
	$(TEX_FILE).aux \
	$(TEX_FILE).log \
	$(TEX_FILE).nav \
	$(TEX_FILE).snm \
	$(TEX_FILE).toc \
	$(TEX_FILE).out \
	$(TEX_FILE).vrb \
	$(TEX_FILE).synctex.gz \
	$(TEX_FILE).fls \
	$(TEX_FILE).fdb_latexmk \
	$(TEX_FILE).blg \
	$(TEX_FILE).bbl \
	*.bbl \
	*.blg

# Define the target for building the PDF
# The PDF depends on the main .tex file and its included .tex files,
# as well as the logo image.
all: $(PDF_FILE)

$(PDF_FILE): $(TEX_FILE).tex preamble.tex math_commands.tex figures/epfl.png
	@echo "Compiling $(TEX_FILE).tex..."
	$(LATEX_COMPILER) $(TEX_FILE)
	$(LATEX_COMPILER) $(TEX_FILE) # Run twice for TOC and cross-references to update

# Define the clean target to remove all auxiliary files and the PDF
clean:
	@echo "Cleaning auxiliary files and $(PDF_FILE)..."
	rm -f $(AUX_FILES) $(PDF_FILE)

# Phony targets: these are not actual files, but commands
.PHONY: all clean
